### ISSUE TITLE
Has this been updated?

### ISSUE THREAD

**Issue by mosskevin** [trickerer01/RV#12]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

I am a complete beginner with no prior experience. I just learned how to use this tool recently, but the rule34video.com latest updates have caused it to consistently give a 403 Forbidden error.

### Provide verbose output that demonstrates the problem (use --log-level trace)

```shell
...
```

**Comment by trickerer01** [comment]
The website is protected by ddos-guard. The problems began recently where entire countries have their access to the website blocked, including mine - any attempt to connect returns error 504 (Gateway Timeout). The reason is unclear, but at the same time even if you have the access you still get 403 error if you use any external tool. Until the error 504 resolves I won't be able to provide any solution for error 403 problem.

For now using proxy is the only way to make RV work.

**Comment by mosskevin** [comment]
Thank you friend,you have my appreciation.
