### ISSUE TITLE
[Question] File Name Structure

### ISSUE THREAD

**Issue by vonhex** [trickerer01/RV#14]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

Would it be possible to save the files with a dash - instead of underscore_? the metadata scaper on Stash is looking for this format: **simple-and-clean_360p** (name with dashes and underscore with quality) if possible it would make my life way easier! Thanks a ton!

**Comment by trickerer01** [comment]
I found Stash app but I've no idea how it works and why this name format is set in stone, so I have a few questions:
- What RV naming flags I'd have to use to compose file name that only contains parts expected by Stash?
- Do I get it right that only the title part has to use dashes instead of underscores?
- Do only spaces need to be converted to dashes or existing underscores (in original title) as well?

**Comment by vonhex** [comment]
You may be right in converting the spaces to dashes. Here is the script doing the work. It's possible to modify but I haven't been able to make it work out of the box with the naming convention

sceneByFragment:
  action: scrapeXPath
  queryURL: https://rule34video.com/video/{filename}
  queryURLReplace:
    filename:
      # Strip out everything after the last _
      - regex: ([^_]+)_.*
        with: $1
  scraper: sceneScraper

**Comment by vonhex** [comment]
Full file
[file.txt](https://github.com/user-attachments/files/17662107/file.txt)

**Comment by trickerer01** [comment]
Looks like the problem is not the underscores in resulting file names. RV grabs original video title, preserving the spaces (`Video title with Upper Case in names and [Special] sybmols`), but it looks like Stash scraper script expects url title slug (`video-title-converted-to-url-slug`). Also I suspect it replaces slashes with underscores (`https://...com/video/12345/video-title-url-slug/` -> `12345_video-title-url-slug_`) and removes the trailing underscore.
I think this can be done with just one additional naming flag to use url title instead of page one.

**Comment by trickerer01** [comment]
Try with https://github.com/trickerer01/RV/commit/39fe9c206b1cadc5c434b501761cc4b5d507f955

Note that you'll have a non-default `-naming` flags ex. `urltitle|quality`

**Comment by vonhex** [comment]
Oh fantastic!

**Comment by vonhex** [comment]
I'll try it tomorrow! Thanks again and ill let you know!

**Comment by vonhex** [comment]
I gave it a try and with that flag it just gives the number I.E. 3586950.mp4

**Comment by vonhex** [comment]
also if I do | for any naming flag I get an error: urltitle|quality 'quality' is not recognized as a command

**Comment by trickerer** [comment]
Oh, you also need to include `title` flag as well since `urltitle` only overrides that (I was testing it using `full|urltitle`). If your console recognizes pipe symbol `|` as a command pipe then you could try putting the parameter in quotes `-naming "title|urltitle|quality"` or use its numeric equivalent `-naming 0x34`

**Comment by vonhex** [comment]
that worked beautifully but only when I remove the ID_ part before the title, any way to kill that part as well?

**Comment by vonhex** [comment]
worst case I can manually remove them via a bulk renamer

**Comment by trickerer** [comment]
No, there is no way to exclude video id from the file name - it's essential for finding already downloaded files, duplicate files and download order

**Comment by vonhex** [comment]
Hmm ok ill work on removing it with regex if I can and manually doing it if
that doesnt work. Thanks a ton for all the help!!
