### ISSUE TITLE
<'aiohttp.client_exceptions.ClientPayloadError'> Response payload is not completed:  FILENAME error #xxx

### ISSUE THREAD

**Issue by iqb4lsp** [trickerer01/RV#2]
Hi, first of all, thanks for this awesome script, when I tried at first it was working perfect with multiple tags without specified artist, but when I tried again on certain artist/model without tags included, it return with `<'aiohttp.client_exceptions.ClientPayloadError'> Response payload is not completed:` with bunch of error number after the filename. Any idea what did I wrong?

**Comment by trickerer01** [comment]
This isn't a problem you could cause by script misuse.

The `<'aiohttp.client_exceptions.ClientPayloadError'> Response payload is not completed` error is a per-file error, caused generally by connection getting closed/reset during download/write process (website could just go down). Just to clarify: search was successful, for this file download link was fetched and download process has started.

This may happen sometimes due to a bunch of different reasons, normally RV should just retry the file.
If this problem persists and you are unable to download using the script but downloading from the website works, provide a full cmdline and console output with `--log-level trace` so it gets fixed.
