### ISSUE TITLE
How do I download a video of one particular author?

### ISSUE THREAD

**Issue by vlad8606** [trickerer01/RV#4]
Hi. How do I download a video of one particular author? 
`https://rule34video.com/models/redmoa/`
That's how it downloads not only this author, but many others.
`python pages.py -pages 5 -quality 1080p -search_art redmoa`
Please help.

**Comment by trickerer01** [comment]
Hi.
Instead of author pages RV uses search engine universally. The problem you've encountered is caused by RV website being flooded with PMVs.
To circumvent this make RV download all the pages but at the same time exclude those compilation tags (there are only two currently):
`python pages.py -pages 999 -quality 1080p -search_art redmoa -compilation -pmv`
This downloads exactly those 120 videos listed on author's 5 pages

**Comment by vlad8606** [comment]
This is exactly what you need. Thank you very much.
